name: Generate APK

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          output-path: cicidApp.apk
          browserstack-upload: false
          upload-to-play-store: false
          gradle-task: 'assembleDebug'
          ruby-version: '3.1.0'
          fastlane-version: '2.225.0'

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: cicidApp.apk