name: Android CI

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Results
        if : failure()
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: app/build/reports


  test:
    name: Unit Tests
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Run Tests
        run: ./gradlew testDebug

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/reports/tests

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          output-path: cicidApp.apk
          browserstack-upload: false
          upload-to-play-store: false
          gradle-task: 'assembleRelease'
          ruby-version: '3.1.0'
          fastlane-version: '2.225.0'

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Signed APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          generate_release_notes: true