name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secrets Length
        run: |
          echo "Length of SIGNING_KEY: ${#SIGNING_KEY}"
          echo "Length of ALIAS: ${#ALIAS}"
          echo "Length of KEY_STORE_PASSWORD: ${#KEY_STORE_PASSWORD}"
          echo "Length of KEY_PASSWORD: ${#KEY_PASSWORD}"
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}